### ISSUE TITLE
Yaw pitch roll value range

### ISSUE THREAD

**Issue by Neethu-pixel** [e-candeloro/Driver-State-Detection#3]
If we manually annotate the head pose, the angle would be in range of [-90, 90] for yaw/pitch/roll.
So how can we evaluate the output Eulers angle (yaw/pitch/roll) with the ground truth data, SInce the output angles ranges between -180 to 180

**Comment by e-candeloro** [comment]
Hello, yes there was a problem in how I calculated the euler angle plus the head reference frame had the z axis flipped so the angles for one of the eulers angles was 180 degrees shifted. 

I fixed this issue creating a new branch and merging it with the master. 

Try to do a git pull and tell me if it solves the problem! 😄

**Comment by e-candeloro** [comment]
update: I also introduced a smoothing factor to reduce a bit the jitter of the keypoints between frames. 
What it does is basically a weighted sum between the keypoints position of the previous frame and the current frame. The default value is 0.5 (so considers the mean value between two frames keypoints position) but you can change that with the argument in the argparser inside the main script.
